---
title: "Survival analysis of KRAS mutations in PAAD samples from the MSK-MetTropism Cohort"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{classify_msk}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(INCOMMON)
library(tidyverse)
```

Some comment about what's in the example MSK data (tujmor types, genes, n samples, n mutations).

```{r}
data = data_MSK %>% filter(tumor_type == 'PAAD')
```

Classify mutations in example data, with no entropy cut-off.

```{r, message=FALSE}
classified_data = lapply((data$sample %>% unique()), function(s){
  
  what = data %>% filter(sample == s)

  x = init(
    mutations = what,
    sample = s,
    tumor_type = unique(what$tumor_type),
    purity = unique(what$purity),
    gene_roles = cancer_gene_census
  )
  
  x = classify(
    x = x,
    priors = pcawg_priors,
    entropy_cutoff = 1,
    rho = 0.01
  )
  
  output = x
  return(output)
})
```

Plot class distribution

```{r}
plot_class_fraction(x = classified_data, tumor_type = 'PAAD', gene = 'KRAS')
```

Fit survival with Kaplan-Meier.

```{r}
km_fit = kaplan_meier_fit(x = classified_data, tumor_type = 'PAAD', gene = 'KRAS')
km_fit$fit[[1]]
```
Fit survival with multivariate Cox regression.

```{r}
cox_fit(x = classified_data, tumor_type = 'PAAD', gene = 'KRAS', covariates = c('age', 'sex', 'tmb'))
```

Plot survival fit

```{r}
plot_survival_analysis(x = classified_data, tumor_type = 'PAAD', gene = 'KRAS', cox_covariates = c('age', 'sex', 'tmb'))
```





